### PR TITLE
Allow sending connection options

### PR DESCRIPTION
**Pull request by matmunn**
This will allow sending kwargs to aioamqp like `verify_ssl` when using a self-signed certificate.

Also fixes a small issue where changing the value of `group_expiry` is ignored.

### CODE REVIEW

**Comment by adamhooper** [comment]
This is great! Thanks.

I understand you need to use a self-signed SSL certificate. There's some thinking to do first.

Basically, are we _absolutely certain_ this feature is needed and worth supporting? First let's rule out three other solutions that might work for you.

*1. The `?verify=cert_none` URI parameter*: https://www.rabbitmq.com/uri-query-parameters.html defines this as a "less-formal companion" to the AMQP URI spec. Does a URI like `amqps://user:pass@host/vhost?verify=cert_none` work for you, without this pull request? If it does, we can add to the documentation. Otherwise, we should first try to make aioamqp itself support the URI. (It seems like a good fit there.)

*2. Is SSL verification actually impossible in your situation?* In particular, can you configure your client to trust your self-signed certificate (or its CA)? Create a directory full of trusted certificates (in my Fedora 29 I'd copy the two symlinks from `/etc/ssl/certs/`, `ca-bundle.crt` and `ca-bundle.trust.crt`, into this new directory), then add your self-signed certificate (in PEM format) to that directory. Run Python with the `SSL_CERT_DIR` environment variable:  `SSL_CERT_DIR=/path/to/this/directory python ...`

(&lt;rant&gt; Why disable SSL verification? SSL prevents passive listening and active MITM attacks. If you disable the MITM mitigation -- which is what verify=false does -- then MITM can be used for passive listening ... meaning SSL with verify=none doesn't prevent any attacks at all: it just makes them more of a hassle. I know, I know, convenience, convenience. Yes, tons of tools today let you disable verification. I expect 20 years from now, that won't be the case.&lt;/rant&gt;) Let's be the change we want to see in the world: let's trust our self-signed certs :).

*3. Would an SSLContext solve this?* The next version of aioamqp will support [SSLContext](https://docs.python.org/3/library/ssl.html#ssl.SSLContext). That gives even more features, such as _client_ certificate validation. In your case, you could support your self-signed certificate for _just the channels_rabbitmq layer_, instead of trusting it across your entire program. We could add a different config option -- for instance, in your case, `'ssl_context': ssl.create_default_context(cafile='/path/to/your/self-signed/cert.pem')`. Or, if you insist on disabling verification, `ssl_context = ssl.create_default_context(); ssl_context.verify_mode = False` and then pass `'ssl_context': ssl_context` as an option.

I'm trying to avoid marrying channels_rabbitmq to aioamqp. aioamqp is one of several AMQP clients, and there's no telling which AMQP client will "win" in the coming years. That means extra work and pateience in the short run, yes ... but fewer problems in the years ahead.

@matmunn 1. Are you able to connect using a URI with `?verify=cert_none` or `?verify=false` or any such query parameter, on the latest released version of channels_rabbitmq? 2. Are you able to make Python trust your self-signed certificate? And 3. how would you feel about adding an `ssl_context` option instead of a `connection_options` option?

Personally, I'm excited about `ssl_context`. I want to wait for the next release of aioamqp, then add that feature. We at CJWorkbench will start using it ourselves, in production; and we'd even be able to unit-test the feature.

In the meantime, I'll leave this pull request open -- anticipating your feedback, and a new version of aioamqp.

**Comment by matmunn** [comment]
1. The AMQP URLs provided to our application are provided in environment variables from our container orchestration platform, and I am unable to modify them myself. I'd be hesitant to simply append URI parameters to the string in case the URL provided changes in the future.

2. It's an internal application and not publicly facing so we're willing to turn off SSL verification for this application.

3. I've been looking at aioamqp and have seen that the next version allows you to pass an `SSLContext` for handling SSL, but the `from_url` function, which is used by channels_rabbitmq, doesn't have this capability yet - it merely checks if  an AMQP URL starts with `amqps`, I can only assume this functionality will be coming though, but I agree that this would be the best option once it's supported properly.

**Comment by adamhooper** [comment]
Thank you for the quick feedback. I'll leave this hanging until the next aioamqp release. I've asked over at https://github.com/Polyconseil/aioamqp/pull/142 where the feature was added, and I've subscribed to their releases so we can jump on this as soon as it happens.

@matmunn Would you like to revise this pull request to implement an `ssl_context` option instead, once aioamqp is released? Otherwise I can do it myself, but it'll take a bit longer.

**Comment by matmunn** [comment]
@adamhooper I see that the aioamqp team still haven't really given you a good answer to your comment and still haven't pushed a new release. Are you still happy to have this PR sit here until that happens?

**Comment by adamhooper** [comment]
Monday I'll test on aioamqp master and advocate for a release there.

**Comment by matmunn** [comment]
Awesome, thanks for this

**Comment by adamhooper** [comment]
Fixed in `v1.1.0` with new `ssl_context` option (see documentation).

We're dogfooding with this one. `tests/test_connection.py` and `ssl/prepare-certs.sh` is an example in which the server and client verify _each other_. SSL is tricky; so if anyone has a hard time solving an SSL-related problem I'd love to add documentation on how to solve it.

@matmunn Thanks for your patience!

**Pull request closed without merging**
