### PR TITLE
Magic values customized

### PR DESCRIPTION
**Pull request by nnseva**
`groups_exchange` option replaces GroupsExchange magic value.
`reconnect_delay` option replaces ReconnectDelay magic value.

### CODE REVIEW

**Comment by adamhooper** [comment]
Thank you for this awesome pull request.

@nnseva Do you absolutely need `reconnect_delay` to be an option? I ask because I'm still considering exponential backoff instead of constant delay; I hesitate to introduce a configuration param only to deprecate once we improve our retry logic.

The `groups_exchange` config option is perfect and I'd merge it in a heartbeat.

**Comment by nnseva** [comment]
> @nnseva Do you absolutely need `reconnect_delay` to be an option?I ask because I'm still considering exponential backoff instead of constant delay; I hesitate to introduce a configuration param only to deprecate once we improve our retry logic.
> 
> The `groups_exchange` config option is perfect and I'd merge it in a heartbeat.

**Comment by nnseva** [comment]
Hi @adamhooper ,

> @nnseva Do you absolutely need `reconnect_delay` to be an option?

Really I've added it just in case, seeing them both together in a header. Really I particularly need only groups_exchange option.

> I ask because I'm still considering exponential backoff instead of constant delay; I hesitate to introduce a configuration param only to deprecate once we improve our retry logic.

It might be some kind of a start value for the exponential backoff or something like this. Also, the backoff might be an option itself.

Anyway, I can remove the `reconnect_delay` option from the doc, or totally from the option list if you need.

**Comment by adamhooper** [comment]
Thanks for the quick response! I'd be thrilled if you could please undo the ReconnectDelay changes and just leave the `groups_exchange` option in this pull request.

... Reconnect configuration will come sooner or later. We can discuss it as a separate issue, though.

**Comment by nnseva** [comment]
done @adamhooper

**Comment by adamhooper** [comment]
Thanks for this awesome pull request. I've just pushed v1.1.2; assuming Travis concurs, it should appear on PyPI in the next few minutes.

**Pull request merged**
